import { LayoutHome } from "layouts";
import Head from "next/head";

const HomePage = () => {
  return (
    <>
      <Head>
        <title>HomePage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LayoutHome>HomePage</LayoutHome>
    </>
  );
};

export default HomePage;
